-- LOGINS

DECLARE @DBPWD VARCHAR(16)
SET @DBPWD = N'[YOURPASSWORDHERE]'		-- RECOMMENDED: CHANGE THE PASSWORD!!!

DECLARE @statement NVARCHAR(250)
IF EXISTS (SELECT name FROM master.sys.server_principals WHERE name = 'ICD2READER')
BEGIN
	
	SELECT @statement = 'DROP LOGIN ICD2READER'
	EXEC sp_executesql @statement
END

SELECT @statement = 'CREATE LOGIN ICD2READER WITH PASSWORD = ''' + (@DBPWD) + ''''
EXEC sp_executesql @statement

USE ICD2DB

DROP USER IF EXISTS ICD2READER

CREATE USER ICD2READER FOR LOGIN ICD2READER;

GO 

EXEC sp_addrolemember db_datareader, ICD2READER